### ISSUE TITLE
Warnings in docs build

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess#110]
Here are the fixes Copilot suggests:

The recent logs indicate that the job was canceled due to the operation being canceled, and there were some warnings and issues during the Sphinx documentation build process. Here are the key points extracted from the logs:

- Several warnings related to missing locale directories.
- Warnings about missing favicon and changes in Sphinx configuration.
- Inline literal and interpreted text warnings in the `ess.reduce.widgets.EssWidget` docstring.
- The document `ess.reduce.uncertainty.UncertaintyBroadcastMode.rst` is referenced in multiple toctrees.
- The job was canceled during the documentation build process.

### Suggested Fixes
1. **Address Missing Locale Directories**: Ensure that the locale directories exist or update the configuration to point to the correct paths.
2. **Fix Missing Favicon**: Add the missing `_static/favicon.ico` file or update the configuration to remove this reference.
3. **Resolve Docstring Warnings**: Fix the inline literal and interpreted text warnings in the `ess.reduce.widgets.EssWidget` docstring.
4. **Toctree References**: Resolve the duplicate toctree references for `ess.reduce.uncertainty.UncertaintyBroadcastMode`.

These changes should help address the warnings and prevent the job from being canceled.

**Comment by SimonHeybrock** [comment]
@jl-wynen You fixed some of these in scipp/essreduce#134, right?

**Comment by jl-wynen** [comment]
I addressed 2 and 3

**Comment by jl-wynen** [comment]
Where do the other two warnings come form? I can see some lines about locales. But there is nothing about uncertainties in the log.

**Comment by SimonHeybrock** [comment]
> Where do the other two warnings come form? I can see some lines about locales. But there is nothing about uncertainties in the log.

Might be a hallucination. Closing for now.
