### ISSUE TITLE
Duplicate detector number?

### ISSUE THREAD

**Issue by jl-wynen** [scipp/ess#118]
It seems like we end up with two identical coords when loading nexus files: `detector_number` and `event_id`. E.g., in the LoKI direct beam workflow:
![Screenshot_20240919_152256](https://github.com/user-attachments/assets/a01d6169-3aa5-4329-91ae-08306470bff1)

Can we skip one of them? That would save some memory and maybe run time. (The arrays are not aliases of each other.)

**Comment by SimonHeybrock** [comment]
I guess this is left over from the grouping mechanism, but on top of my head I don't know why this happens. Please investigate! I think `event_id` should not be there.

**Comment by jokasimr** [comment]
`event_id` is added when the events are grouped by pixel, just like @SimonHeybrock said.
It seems `da.group(event_ids)` adds a coordinate with the same name as the dimension of `event_ids`.

Then the detector coordinates are added to the dataarray, see https://github.com/scipp/essreduce/blob/c91e01a2af2f738f7b7fd102051f7f99bad7112b/src/ess/reduce/nexus/workflow.py#L394.

But the `event_id` is never removed, and that is why they are still there.
