### ISSUE TITLE
[Amor only] Scale R(Q) so that reflectivity is 1 for low Q

### ISSUE THREAD

**Issue by jokasimr** [scipp/ess#313]
The reflectivity curve R(Q) should be 1.0 for Q->0. For data from Amor this is typically not the case. The reason is that the reference measurement and the sample measurement might have seen different neutron fluxes at the sample. If the sample sees a higher flux than the reference then the reflectivity of the sample will seem to be larger than 1, and vice versa.

To compensate for this we should scale the entire R(Q) curve so that it goes to 1 when Q->0. 

This will probably not be relevant for estia because they will (probably) have monitors that can be used to do this normalization.

**Comment by paracini** [comment]
Superseded by scipp/ess#303
