### ISSUE TITLE
Support concatenating files

### ISSUE THREAD

**Issue by jokasimr** [scipp/ess#314]
Several smaller measurements can sometimes be treated as one measurement with a larger event list.
The interface should probably consist of a list of files to concatenate.
The details needs to be worked out. Probably needs discussion with IDS.

**Comment by SimonHeybrock** [comment]
See https://scipp.github.io/esssans/generated/functions/ess.sans.with_sample_runs.html and its implementation for a similar requirement in ESSsans.
