### ISSUE TITLE
Mapping of `event_time_zero` to `tof` modifies input data

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess#347]
Ran into this when working with streaming data. Does not affect "static" workflows.

**Comment by nvaytet** [comment]
Can you point to where the issue is in the code/workflow?

**Comment by SimonHeybrock** [comment]
https://github.com/scipp/esssans/blob/9434614cf0e2db615779c8d83e375094b059174e/src/ess/loki/general.py#L61, but I think there is a similar problem in the ISIS folder.
