### ISSUE TITLE
Save data in TOF to CIF

### ISSUE THREAD

**Issue by jl-wynen** [scipp/ess#506]
We need to write the final results in TOF so that analysis software can read them. In the CIF writer, this means changing from saving `pd_proc` to `pr_meas` with the appropriate fields.

**Comment by jl-wynen** [comment]
Currently blocked because we don't have an implementation for converting back to TOF. But this issue needs to be resolved quickly once we have that.

**Comment by SimonHeybrock** [comment]
Is the wavelength modified after computing it? If not we can just keep the TOF coord when computing wavelength?
