### ISSUE TITLE
Handle sub-pixel precisions

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/ess#59]
The latest files we got from the filewriters for ODIN seems to have physical pixel ids, not the processed finer pixels.
We should check with ECDC what the `event_id` means in the file, since it can change.

**Sub-pixel precisions**

**Comment by YooSunYoung** [comment]
We checked this with ECDC and they are implementing the sub-pixels. 
We still have to make sure how to retrieve and use the sub-pixel related information in the workflow.

**Comment by SimonHeybrock** [comment]
To me it sounded like we will not have to do anything, i.e., ECDC will simply write an NXdetector with more pixels and detector numbers?

**Comment by YooSunYoung** [comment]
I'm not sure if we need to decide the pixel sizes/positions based on the sub-pixel resolutions. or if the geometry will also be changed based on them.
Last time I checked, they couldn't decide. I'll close it once it's all sorted.

**Comment by SimonHeybrock** [comment]
Not sure it is valid NeXus unless they do?

**Comment by YooSunYoung** [comment]
Sub-pixel will be handled before they are written into a file. 
So this is not relevant anymore. (at least for now.)
